# Generated by Django 2.0.5 on 2018-06-13 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kandidat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=30)),
                ('prijmeni', models.CharField(max_length=30)),
                ('trida', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=70)),
                ('token', models.CharField(max_length=50)),
                ('voted', models.CharField(default='NO')),
            ],
        ),
        migrations.CreateModel(
            name='Vitezove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kandidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hlasovani.Kandidat')),
            ],
        ),
        migrations.AddField(
            model_name='kandidat',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hlasovani.Student'),
        ),
    ]
