# Generated by Django 2.0.5 on 2018-06-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=30)),
                ('prijmeni', models.CharField(max_length=30)),
                ('trida', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=70)),
                ('token', models.CharField(max_length=50)),
                ('votes', models.IntegerField(default=0)),
                ('voted', models.BooleanField(default=False)),
            ],
        ),
    ]
