# Generated by Django 2.0.5 on 2018-06-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlasovani', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='voted',
            field=models.CharField(default='NO', max_length=3),
        ),
    ]
