# Generated by Django 2.0.5 on 2018-06-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlasovani', '0002_auto_20180613_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('data', models.FileField(upload_to='uploaded_files')),
            ],
        ),
    ]
