# Generated by Django 2.0.5 on 2018-06-13 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hlasovani', '0003_datafile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafile',
            old_name='name',
            new_name='nazev',
        ),
        migrations.RenameField(
            model_name='datafile',
            old_name='data',
            new_name='soubor',
        ),
        migrations.AddField(
            model_name='datafile',
            name='konec_hlasovani',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datafile',
            name='konec_kandidovani',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='token',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='voted',
            field=models.BooleanField(default=False),
        ),
    ]
