# Generated by Django 2.0.5 on 2018-06-14 15:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hlasovani', '0004_auto_20180613_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='token',
            field=models.CharField(default=uuid.UUID('bcd34a35-543f-431d-88f8-c0e45dcba6cd'), max_length=50),
        ),
    ]
